name: Generate xml sitemap

on:
  push:
    branches:
      - main  # Se activa cada vez que subes algo a la rama principal

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: generate-sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate XML Sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://arcosv.com.ar/
       
    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add sitemap.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated sitemap update" && git push)
